name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Linter
        run: docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.31.0 golangci-lint run -v
      - name: Tests
        run: go test